ALTER TABLE empre ADD COLUMN logo VARCHAR(255) DEFAULT NULL AFTER mail;
ALTER TABLE empre ADD COLUMN web VARCHAR(255) DEFAULT NULL AFTER logo;

ALTER TABLE admin_sucursales
  ADD COLUMN direccion VARCHAR(255) DEFAULT NULL AFTER iddepo,
  ADD COLUMN telefono VARCHAR(60) DEFAULT NULL AFTER direccion,
  ADD COLUMN email VARCHAR(190) DEFAULT NULL AFTER telefono;
