-- Logo y web de la empresa (se muestran en header/hero). Idempotente.
ALTER TABLE empre ADD COLUMN IF NOT EXISTS logo VARCHAR(255) DEFAULT NULL AFTER mail;
ALTER TABLE empre ADD COLUMN IF NOT EXISTS web VARCHAR(255) DEFAULT NULL AFTER logo;

ALTER TABLE admin_sucursales
  ADD COLUMN IF NOT EXISTS direccion VARCHAR(255) DEFAULT NULL AFTER iddepo,
  ADD COLUMN IF NOT EXISTS telefono VARCHAR(60) DEFAULT NULL AFTER direccion,
  ADD COLUMN IF NOT EXISTS email VARCHAR(190) DEFAULT NULL AFTER telefono;